name: freightlinkzw
region: lon
services:
- name: web
  github:
    branch: main
    repo: codeguru2025/freightlink
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  health_check:
    http_path: /health
  build_command: npm install && npm run build
  run_command: npm run start
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: PAYNOW_INTEGRATION_ID
    scope: RUN_TIME
    value: "REPLACE_WITH_PAYNOW_INTEGRATION_ID"
  - key: PAYNOW_INTEGRATION_KEY
    scope: RUN_TIME
    value: "REPLACE_WITH_PAYNOW_INTEGRATION_KEY"
  - key: PAYNOW_EMAIL
    scope: RUN_TIME
    value: "REPLACE_WITH_PAYNOW_MERCHANT_EMAIL"

jobs:
- name: db-migrate
  kind: PRE_DEPLOY
  github:
    branch: main
    repo: codeguru2025/freightlink
  build_command: npm install --include=dev
  run_command: npx tsx server/migrate.ts
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
